name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - uses: dylanvann/publish-github-action@973d5c2eec5df00513bb013e4424eaf04117ebd1 # v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
