name: Test
on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: ESLint
        run: yarn run eslint
      - name: Prettier
        run: yarn run check-prettier
